"use client"
import { CheckCircle2, AlertCircle, Trash2, Loader2, Brain, Download, FileText } from "lucide-react"
import { Button } from "@/components/ui/button"

interface CoconutRecord {
  id: string
  weight: number
  diameter: number
  height: number
  majorAxis: number
  minorAxis: number
  volume: number
  density: number
  waterContent: number
  shellColor: string
  shakeSound: string
  moldSpots: boolean
  cracksDamage: boolean
  score: number
  grade: string
  issues: string[]
  recommendations: string[]
  createdAt: string
  mlConfidence?: number
  geminiAnalysis?: string
  predictions?: any
}

interface CoconutHistoryProps {
  history: CoconutRecord[]
  loading: boolean
  selectedId?: string
  onSelectRecord: (record: CoconutRecord) => void
  onDeleteRecord: (id: string) => void
}

export function CoconutHistory({ history, loading, selectedId, onSelectRecord, onDeleteRecord }: CoconutHistoryProps) {
  const getGradeColor = (grade: string) => {
    if (grade === "A") return "text-green-600"
    if (grade === "B") return "text-blue-600"
    if (grade === "C") return "text-yellow-600"
    return "text-red-600"
  }

  const getGradeBgColor = (grade: string) => {
    if (grade === "A") return "bg-green-50 border-green-200"
    if (grade === "B") return "bg-blue-50 border-blue-200"
    if (grade === "C") return "bg-yellow-50 border-yellow-200"
    return "bg-red-50 border-red-200"
  }

  const downloadAsTxt = (record: CoconutRecord) => {
    const content = `COCONUT QUALITY ANALYSIS REPORT
=================================
ID: ${record.id}
Date: ${new Date(record.createdAt).toLocaleString()}
---------------------------------
PHYSICAL METRICS:
Grade: ${record.grade}
Score: ${record.score}/100
Weight: ${record.weight}g
Dimensions: ${record.majorAxis}cm (L) x ${record.minorAxis}cm (W) x ${record.height}cm (H)
Volume: ${record.volume} cm³
Density: ${record.density} g/cm³
Water Level: ${record.waterContent}
---------------------------------
ASSESSMENT DETAILS:
Shell Color: ${record.shellColor}
Mold Spots: ${record.moldSpots ? "Yes" : "No"}
Cracks/Damage: ${record.cracksDamage ? "Yes" : "No"}
---------------------------------
ISSUES:
${record.issues.length > 0 ? record.issues.map(i => `- ${i}`).join('\n') : "None detected"}

RECOMMENDATIONS:
${record.recommendations.length > 0 ? record.recommendations.map(r => `- ${r}`).join('\n') : "Continue standard processing"}
---------------------------------
AI ANALYSIS:
${record.geminiAnalysis || "No AI analysis available."}
=================================
Report generated by Coconut Quality Checker System`

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `coconut-report-${record.id.slice(0, 8)}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const downloadFullHistory = () => {
    let content = `COCONUT ASSESSMENT HISTORY SUMMARY
TOTAL RECORDS: ${history.length}
GENERATED ON: ${new Date().toLocaleString()}
================================================================================\n\n`

    history.forEach((record, index) => {
      content += `${index + 1}. [${new Date(record.createdAt).toLocaleDateString()}] ID: ${record.id.slice(0, 8)} | Grade: ${record.grade} | Score: ${record.score}/100 | Weight: ${record.weight}g | Volume: ${record.volume}cm³ | Density: ${record.density}g/cm³\n`
    })

    content += "\n\n================================================================================\nEnd of Report"

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `coconut-history-summary.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-bold text-gray-800">Assessment History</h3>
        {history.length > 0 && (
          <Button 
            variant="outline" 
            size="sm" 
            onClick={downloadFullHistory}
            className="text-green-700 border-green-200 hover:bg-green-50"
          >
            <Download className="w-4 h-4 mr-2" />
            Download All (.txt)
          </Button>
        )}
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-8">
          <Loader2 className="w-5 h-5 animate-spin text-gray-400" />
        </div>
      ) : history.length === 0 ? (
        <p className="text-sm text-gray-500 text-center py-8">No assessments yet</p>
      ) : (
        <div className="space-y-3">
          {history.map((record) => (
            <div
              key={record.id}
              className={`p-4 rounded-lg border-2 cursor-pointer transition-all ${
                selectedId === record.id
                  ? "border-green-500 bg-green-50 shadow-md"
                  : `border-gray-200 hover:border-green-300 bg-white ${getGradeBgColor(record.grade)}`
              }`}
              onClick={() => onSelectRecord(record)}
            >
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-center gap-3">
                  {record.grade === "A" ? (
                    <CheckCircle2 className="w-5 h-5 text-green-600 flex-shrink-0" />
                  ) : record.grade === "B" ? (
                    <CheckCircle2 className="w-5 h-5 text-blue-600 flex-shrink-0" />
                  ) : record.grade === "C" ? (
                    <AlertCircle className="w-5 h-5 text-yellow-600 flex-shrink-0" />
                  ) : (
                    <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0" />
                  )}
                  <div>
                    <p className={`text-lg font-bold ${getGradeColor(record.grade)}`}>
                      Grade {record.grade}
                    </p>
                    <p className="text-xs text-gray-900">
                      {new Date(record.createdAt).toLocaleString()}
                    </p>
                  </div>
                </div>
                <div className="text-right">
                  <p className="text-2xl font-bold text-green-600">{record.score}</p>
                  <p className="text-xs text-gray-900">/ 100</p>
                </div>
              </div>

              {/* Details */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-xs mb-3 border-y border-gray-100 py-2">
                <div>
                  <span className="text-gray-500 block mb-1">Dimensions (LxWxH)</span>
                  <span className="font-bold text-gray-900 block lg:inline">
                    {record.majorAxis} x {record.minorAxis} x {record.height}
                  </span>
                  <span className="text-gray-500 ml-1">cm</span>
                </div>
                <div>
                  <span className="text-gray-500 block mb-1">Weight</span>
                  <span className="font-bold text-gray-900">{record.weight}</span>
                  <span className="text-gray-500 ml-1">g</span>
                </div>
                <div>
                  <span className="text-gray-500 block mb-1">Volume (V)</span>
                  <span className="font-bold text-gray-900">{record.volume}</span>
                  <span className="text-gray-500 ml-1">cm³</span>
                </div>
                <div>
                  <span className="text-gray-500 block mb-1">Density (ρ)</span>
                  <span className="font-bold text-gray-900">{record.density}</span>
                  <span className="text-gray-500 ml-1">g/cm³</span>
                </div>
                <div>
                  <span className="text-gray-500 block mb-1">Water Level</span>
                  <span className="font-bold text-gray-900">{record.waterContent}</span>
                  <span className="text-gray-500 ml-1">L</span>
                </div>
              </div>

              {/* Issues */}
              {record.issues && record.issues.length > 0 && (
                <div className="mt-2 p-2 bg-red-50 rounded border border-red-200">
                  <p className="text-xs font-semibold text-red-700 mb-1">Issues:</p>
                  <ul className="text-xs text-red-600 space-y-1">
                    {record.issues.map((issue, i) => (
                      <li key={i}>• {issue}</li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Gemini Analysis */}
              {selectedId === record.id && record.geminiAnalysis && (
                <div className="mt-3 p-3 bg-blue-50 rounded border border-blue-200">
                  <div className="flex items-center gap-2 mb-2">
                    <Brain className="w-4 h-4 text-blue-600" />
                    <p className="text-xs font-bold text-blue-800 underline decoration-blue-300">Detailed AI Analysis Report</p>
                  </div>
                  <p className="text-xs text-blue-900 whitespace-pre-wrap leading-relaxed">{record.geminiAnalysis}</p>
                  
                  <Button 
                    variant="ghost" 
                    size="sm" 
                    onClick={(e) => {
                      e.stopPropagation();
                      downloadAsTxt(record);
                    }}
                    className="mt-3 w-full border border-blue-200 text-blue-700 hover:bg-blue-100"
                  >
                    <FileText className="w-3 h-3 mr-2" />
                    Download Individual Report (.txt)
                  </Button>
                </div>
              )}

              {/* Recommendations */}
              {selectedId === record.id && record.recommendations && record.recommendations.length > 0 && (
                <div className="mt-2 p-2 bg-green-50 rounded border border-green-200">
                  <p className="text-xs font-semibold text-green-700 mb-1">Recommendations:</p>
                  <ul className="text-xs text-green-600 space-y-1">
                    {record.recommendations.map((rec, i) => (
                      <li key={i}>• {rec}</li>
                    ))}
                  </ul>
                </div>
              )}

              {selectedId === record.id && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={(e) => {
                    e.stopPropagation()
                    onDeleteRecord(record.id)
                  }}
                  className="w-full mt-3 text-red-600 hover:text-red-700 hover:bg-red-50"
                >
                  <Trash2 className="w-3 h-3 mr-1" />
                  Delete Assessment
                </Button>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
